name: Update flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 07 * * 6" # At 07:00 on Saturday

jobs:
  update-flake-inputs:
    runs-on: nixos
    steps:
      - uses: https://git.akotro.dev/actions/checkout@v6
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          echo "https://akotro:${{ secrets.FJ_TOKEN }}@git.akotro.dev" > ~/.git-credentials
          git config --global credential.helper store
          git config --global user.name "forgejo-bot"
          git config --global user.email "forgejo@users.noreply.git"

      - name: Update flake inputs
        run: |
          nix flake update --commit-lock-file

      - name: Create PR
        uses: https://git.akotro.dev/actions/create-pr@main
        with:
          token: ${{ secrets.FJ_TOKEN }}
          pr-branch: chore/update-flake
          pr-title: "flake: updates"
          pr-body: "`flake.lock` updates"
          pr-assignee: akotro
          pr-condition-cmd: "git log origin/main..HEAD --oneline"
