name: Deploy Prod

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches: [ "main" ]

env:
  HOSTNAME: tithe
  FLAKE_INPUT: ratings

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production

    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        # root-reserve-mb: 512
        # swap-size-mb: 1024
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_RATINGS_DEPLOY_KEY }}
          ${{ secrets.SSH_DOTFILES_DEPLOY_KEY }}
          ${{ secrets.SSH_NVIM_DEPLOY_KEY }}
          ${{ secrets.SSH_SITE_DEPLOY_KEY }}

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        version: 1.78.1

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://hyprland.cachix.org https://nixcache.tithe.stream
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nixcache.tithe.stream:NaU/9+NHx87UVq6ypmKp2++ny/uSlQvl/7n86FY0s00=
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Checkout external repository
      uses: actions/checkout@v4
      with:
        repository: 'akotro/nixcfg'
        token: ${{ secrets.GIT_NIXCFG_PAT }}
        ref: 'main'

    - name: Update flake input
      run: |
        nix flake lock --accept-flake-config --update-input $FLAKE_INPUT

    - name: Add hostname to known hosts
      id: ssh-known-hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan $HOSTNAME >> ~/.ssh/known_hosts

    - name: Build and deploy
      run: |
        set -euxo pipefail
        nix run github:serokell/deploy-rs -- --skip-checks .#$HOSTNAME.system -- --accept-flake-config

    - name: Commit and push changes
      if: success()
      run: |
        git fetch --prune origin
        git merge origin/main --ff-only
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Ratings Deploy Prod"
        git add .
        git commit -m "chore: update $FLAKE_INPUT flake input" -a || echo "No changes to commit"
        git push

